baseURL: http://something-fresh.org/
languageCode: en-us
title: Martify
theme: hugo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/logo-martify.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Mercado em Casa.
    # Hero subtitle (optional)
    subtitle: Transforme sua casa em um mini mercado e ganhe dinheiro com isso, venda os produtos mais famosos sem sair de casa.
    # Button text
    buttontext: Tenho interesse
    # Where the main hero button links to
    image: illustrations/martify.svg
    buttonlink: "#form-email"
    # Hero image (from static/images/___)
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - coca
    - nestle2
    - itambe2
    - skol2
    - unilever
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Participar
    url: "#form-email"
    button: true
  section1:
    title: Faça parte da revolução
    subtitle: comece a ganhar dinheiro já
    tiles:
    - title: Rápido
      icon: mouse-globe
      text: Cadastra-se na plataforma em apenas alguns cliques
      url: /
      buttonText: Clique e veja
    - title: Fácil
      icon: laptop-cloud
      text: Só precisa de um celular ou um computador
      url: /
      buttonText: Faça parte
    - title: Lucrativo
      icon: plug-cloud
      text: Ganhe dinheiro sem sair de casa, é bem fácil
      url: /
      buttonText: Comece já
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: O que você precisar
    subtitle: em um único lugar
    image: illustrations/mockups/app-mobile.svg
    buttonText: Faça parte
    buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
